apiVersion: v1
kind: Secret
metadata:
  name: elastalert2-secrets
  namespace: elastic-system
type: Opaque
stringData:
  ES_PASSWORD: "2qPz8BaA522ZKiQ18U059LeN"
  SMTP_HOST: "mailhog.elastic-system.svc"
  SMTP_PORT: "1025"
  SMTP_TLS: "false"
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  SMTP_FROM: "alerts@YOUR_DOMAIN"
  ALERT_EMAIL_TO: "smairio98@gmail.com"
