apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 56.6.2
      helm:
        valueFiles:
          - $values/monitoring/values.yaml
    - repoURL: https://github.com/smairio/gitops-cluster-services.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/smairio/gitops-cluster-services.git
      targetRevision: HEAD
      path: monitoring
      directory:
        include: '{ingress.yaml,prometheus-ingress.yaml,externalsecret-*.yaml}'

  # ===========================================================================
  # Ignore differences for ESO-managed secrets
  # ESO continuously updates secrets causing OutOfSync
  # ===========================================================================
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
        - /metadata/annotations
        - /metadata/labels
      managedFieldsManagers:
        - external-secrets
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .status
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.target.deletionPolicy
        - .metadata.finalizers

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
