apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-domain
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-domain
    creationPolicy: Owner
  data:
    - secretKey: domain
      remoteRef:
        key: prod/ha-k8s
        property: DOMAIN_NAME
