apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: redis

  sources:
    # Redis Helm chart
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 24.1.0
      helm:
        valueFiles:
          - $values/redis/values.yaml

    # Values reference
    - repoURL: https://github.com/smairio/gitops-cluster-services.git
      targetRevision: main
      ref: values

    # ExternalSecret manifest
    - repoURL: https://github.com/smairio/gitops-cluster-services.git
      targetRevision: main
      path: redis
      directory:
        include: 'externalsecret.yaml'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
